#!/usr/bin/env python3
"""Generate a simple futuristic city OBJ model with skyscrapers, parks and flying cars."""

from __future__ import annotations

import math
import random
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Face:
    verts: tuple[int, ...]
    material: str


class ObjBuilder:
    def __init__(self) -> None:
        self.vertices: list[tuple[float, float, float]] = []
        self.faces: list[Face] = []

    def add_vertex(self, x: float, y: float, z: float) -> int:
        self.vertices.append((x, y, z))
        return len(self.vertices)

    def add_face(self, verts: tuple[int, ...], material: str) -> None:
        self.faces.append(Face(verts=verts, material=material))

    def add_box(
        self,
        center_x: float,
        center_y: float,
        width: float,
        depth: float,
        height: float,
        material: str,
        base_z: float = 0.0,
    ) -> None:
        hx = width / 2.0
        hy = depth / 2.0

        # Bottom
        v1 = self.add_vertex(center_x - hx, center_y - hy, base_z)
        v2 = self.add_vertex(center_x + hx, center_y - hy, base_z)
        v3 = self.add_vertex(center_x + hx, center_y + hy, base_z)
        v4 = self.add_vertex(center_x - hx, center_y + hy, base_z)

        # Top
        top_z = base_z + height
        v5 = self.add_vertex(center_x - hx, center_y - hy, top_z)
        v6 = self.add_vertex(center_x + hx, center_y - hy, top_z)
        v7 = self.add_vertex(center_x + hx, center_y + hy, top_z)
        v8 = self.add_vertex(center_x - hx, center_y + hy, top_z)

        # Faces (quads)
        self.add_face((v1, v2, v3, v4), material)  # bottom
        self.add_face((v5, v6, v7, v8), material)  # top
        self.add_face((v1, v2, v6, v5), material)
        self.add_face((v2, v3, v7, v6), material)
        self.add_face((v3, v4, v8, v7), material)
        self.add_face((v4, v1, v5, v8), material)

    def add_hex_pad(self, cx: float, cy: float, radius: float, z: float, material: str) -> None:
        center = self.add_vertex(cx, cy, z)
        ring = []
        for i in range(6):
            angle = math.radians(60 * i)
            ring.append(self.add_vertex(cx + radius * math.cos(angle), cy + radius * math.sin(angle), z))
        for i in range(6):
            self.add_face((center, ring[i], ring[(i + 1) % 6]), material)

    def write(self, obj_path: Path, mtl_name: str) -> None:
        with obj_path.open("w", encoding="utf-8") as f:
            f.write("# Futuristic city generated by generate_future_city_obj.py\n")
            f.write(f"mtllib {mtl_name}\n\n")

            for vx, vy, vz in self.vertices:
                f.write(f"v {vx:.4f} {vy:.4f} {vz:.4f}\n")

            f.write("\n")
            active_material = None
            for face in self.faces:
                if face.material != active_material:
                    f.write(f"usemtl {face.material}\n")
                    active_material = face.material
                indices = " ".join(str(v) for v in face.verts)
                f.write(f"f {indices}\n")


def build_city(seed: int = 42) -> ObjBuilder:
    rng = random.Random(seed)
    obj = ObjBuilder()

    # Ground base
    obj.add_box(0, 0, width=160, depth=160, height=1, material="ground", base_z=-1)

    # City grid with parks and towers
    cell_size = 18
    half = 3
    for gx in range(-half, half + 1):
        for gy in range(-half, half + 1):
            x = gx * cell_size
            y = gy * cell_size
            park = (gx + gy) % 4 == 0

            if park:
                obj.add_box(x, y, width=14, depth=14, height=0.4, material="park", base_z=0)
                # Trees as small columns
                for _ in range(4):
                    tx = x + rng.uniform(-5.0, 5.0)
                    ty = y + rng.uniform(-5.0, 5.0)
                    obj.add_box(tx, ty, width=1.2, depth=1.2, height=rng.uniform(2.2, 3.5), material="tree")
            else:
                towers = rng.randint(1, 3)
                for _ in range(towers):
                    tx = x + rng.uniform(-4.0, 4.0)
                    ty = y + rng.uniform(-4.0, 4.0)
                    width = rng.uniform(3.5, 7.0)
                    depth = rng.uniform(3.5, 7.0)
                    height = rng.uniform(18.0, 54.0)
                    obj.add_box(tx, ty, width=width, depth=depth, height=height, material="tower")

                    # Rooftop heli/aircar pad
                    if height > 30:
                        obj.add_hex_pad(tx, ty, radius=min(width, depth) * 0.4, z=height + 0.05, material="pad")

    # Elevated sky lanes
    for lane_y in (-28, 0, 28):
        obj.add_box(0, lane_y, width=145, depth=2.0, height=0.6, material="sky_lane", base_z=28)

    # Flying cars (simple stylized boxes)
    car_positions = [
        (-45, -28, 30.5),
        (-10, 0, 30.8),
        (18, 28, 31.0),
        (52, 0, 30.7),
        (34, -28, 30.9),
    ]
    for cx, cy, cz in car_positions:
        obj.add_box(cx, cy, width=3.2, depth=1.4, height=0.8, material="car", base_z=cz)
        # Car canopy
        obj.add_box(cx, cy, width=1.8, depth=1.0, height=0.45, material="glass", base_z=cz + 0.8)

    return obj


def write_materials(path: Path) -> None:
    materials = """# Futuristic city materials
newmtl ground
Kd 0.10 0.10 0.13
Ka 0.03 0.03 0.04
Ks 0.05 0.05 0.05

newmtl tower
Kd 0.45 0.52 0.62
Ka 0.12 0.14 0.18
Ks 0.35 0.35 0.40

newmtl park
Kd 0.18 0.45 0.22
Ka 0.05 0.15 0.06
Ks 0.05 0.10 0.05

newmtl tree
Kd 0.10 0.35 0.10
Ka 0.04 0.10 0.04
Ks 0.03 0.05 0.03

newmtl sky_lane
Kd 0.20 0.28 0.36
Ka 0.06 0.08 0.10
Ks 0.25 0.30 0.35

newmtl car
Kd 0.85 0.25 0.25
Ka 0.20 0.06 0.06
Ks 0.50 0.40 0.40

newmtl glass
Kd 0.55 0.75 0.90
Ka 0.10 0.14 0.18
Ks 0.60 0.65 0.70

newmtl pad
Kd 0.95 0.85 0.20
Ka 0.20 0.16 0.05
Ks 0.35 0.30 0.10
"""
    path.write_text(materials, encoding="utf-8")


def main() -> None:
    out_dir = Path(__file__).resolve().parent
    obj_file = out_dir / "future_city.obj"
    mtl_file = out_dir / "future_city.mtl"

    city = build_city(seed=2026)
    city.write(obj_file, mtl_name=mtl_file.name)
    write_materials(mtl_file)

    print(f"Created: {obj_file}")
    print(f"Created: {mtl_file}")
    print(f"Vertices: {len(city.vertices)}")
    print(f"Faces: {len(city.faces)}")


if __name__ == "__main__":
    main()
